package com.sarfaraz.opticart.security.enums;

public enum UserPermission {
    PERM_RW_ALL,
    PERM_RW_USER,
    PERM_RO_USER,
    PERM_RW_ROLE,
    PERM_RO_ROLE,
    PERM_RW_PERMISSION,
    PERM_RO_PERMISSION,
    PERM_RW_PRODUCT,
    PERM_RO_PRODUCT,
    PERM_RW_STOCK,
    PERM_RO_STOCK,
    PERM_RW_ORDER,
    PERM_RO_ORDER,
    PERM_RW_PRESCRIPTION,
    PERM_RO_PRESCRIPTION,
    PERM_RO_ANALYTICS,
    PERM_RW_WISHLIST,
    PERM_RO_WISHLIST,
    PERM_RW_CART,
    PERM_RO_CART
}
